<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>
<br></br>

# Neural Networks

## *Data Science Unit 4 Sprint 2 Assignment 1*

## Define the Following:
You can add image, diagrams, whatever you need to ensure that you understand the concepts below.

### Input Layer: node(s) that can represent the input or output of an neural net
### Hidden Layer: node(s) who do not have a discreet output or input. they handle weighting
### Output Layer: output node(s) of neural net and can be used to train or feed back into the input layer
### Neuron: represents a node in the net, and will take input and make output.
### Weight: input that creates bias in a net
### Activation Function: activates the output, given the result of a net of bias
### Node Map: generlized map of flow from input to output in a neural net design
### Perceptron: single neuron nuerual net


## Inputs -> Outputs

## Explain the flow of information through a neural network from inputs to outputs. Be sure to include: inputs, weights, bias, and activation functions. How does it all flow from beginning to end?

## My Answer Here
### input -> hidden layer x weight -> = bias x -> output -(>activation function)  
### this flow can be encapsulated as a single neuron or a network of specially crated hidden layers, but the principle remains the same input flows to/through layers and creates a bias, that bias is fed into the next layer, or the output if there are no other layers, and is captured by the activation function

## Write your own perceptron code that can correctly classify (99.0% accuracy) a NAND gate. 

| x1 | x2 | y |
|----|----|---|
| 0  | 0  | 1 |
| 1  | 0  | 1 |
| 0  | 1  | 1 |
| 1  | 1  | 0 |

In [2]:
import pandas as pd
import numpy as np

In [6]:
##### Your Code Here #####
np.random.seed(42)

data = np.array([
    [0,0,1],
    [1,0,1],
    [0,1,1],
    [1,1,1]
])


inputs = np.array(([1], [1], [1], [0]))

In [10]:
# logistic function that enables learning 
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# uses derivative of sigmoid to find loss in a step
def loss_function(x):
    s = sigmoid(x)
    return s * (1 - s)

# activates ouput by taking product of inputs and weights
def activation(x, weight):
    return sigmoid(np.dot(x, weight))

# lol more abstract becasue it sless clear, but takes a 
# error and looks at loss. thats it thats my understnading.
def backpropagation(activation, y):
    error = y - activation
    return error * loss_function(y)

In [9]:
weights = 2 * np.random.random((3,1)) - 1
weights

array([[ 0.19731697],
       [-0.68796272],
       [-0.68801096]])

In [12]:
for iteration in range(10000):
    
    # Activate!
    output = activation(data, weights)
    backprop = backpropagation(output, inputs)
    weights += np.dot(data.T, backprop)
    
print("Weights after training")
print(weights)

print("Output after train")
print(output)

Weights after training
[[-8.57694879]
 [-8.57694882]
 [12.91425466]]
Output after train
[[0.99999753]
 [0.9870905 ]
 [0.9870905 ]
 [0.01421508]]


## Implement your own Perceptron Class and use it to classify a binary dataset: 
- [The Pima Indians Diabetes dataset](https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv) 

You may need to search for other's implementations in order to get inspiration for your own. There are *lots* of perceptron implementations on the internet with varying levels of sophistication and complexity. Whatever your approach, make sure you understand **every** line of your implementation and what its purpose is.

In [19]:
diabetes = pd.read_csv('https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv')
diabetes.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

Although neural networks can handle non-normalized data, scaling or normalizing your data will improve your neural network's learning speed. Try to apply the sklearn `MinMaxScaler` or `Normalizer` to your diabetes dataset. 

In [29]:
from sklearn.preprocessing import MinMaxScaler, Normalizer

feats = list(diabetes)[:-1]

X = MinMaxScaler().fit_transform(diabetes[feats])
X = np.hstack((X, np.ones((diabetes.shape[0],1))))
y = diabetes[['Outcome']]
X

array([[0.35294118, 0.74371859, 0.59016393, ..., 0.23441503, 0.48333333,
        1.        ],
       [0.05882353, 0.42713568, 0.54098361, ..., 0.11656704, 0.16666667,
        1.        ],
       [0.47058824, 0.91959799, 0.52459016, ..., 0.25362938, 0.18333333,
        1.        ],
       ...,
       [0.29411765, 0.6080402 , 0.59016393, ..., 0.07130658, 0.15      ,
        1.        ],
       [0.05882353, 0.63316583, 0.49180328, ..., 0.11571307, 0.43333333,
        1.        ],
       [0.05882353, 0.46733668, 0.57377049, ..., 0.10119556, 0.03333333,
        1.        ]])

In [34]:
##### Update this Class #####

class Perceptron(object):
    
    def __init__(self, niter = 10, rate=0.01):
        self.niter = niter
        self.rate = rate
        
    def __sigmoid(self, x):
        self.x = x
        return 1 / (1 + np.exp(-self.x))
    
    def __sigmoid_derivative(self, x):
        self.x = sigmoid(x)
        return self.x * (1 - self.x)

    def fit(self, X, y):
        """Fit training data
        X : Training vectors, X.shape : [#samples, #features]
        y : Target values, y.shape : [#samples]
        """

        # Randomly Initialize Weights
        self.weights = np.zeros((X.shape[1], 1))

        for i in range(self.niter):
            output = self.__sigmoid(np.dot(X, self.weights))
            error = self.rate * (y - output)
            adjustments = error * self.__sigmoid_derivative(output)
            self.weights += np.dot(X.T, adjustments)


    def predict(self, X):
        """Return class label after unit step"""
        
        return self.__sigmoid(np.dot(X, self.weights))

In [36]:
p = Perceptron(niter=1000)
p.fit(X, y)


In [39]:
# pred = p.predict(X)
pred = (p.predict(X) + 0.5).astype(int)

In [40]:
from sklearn.metrics import accuracy_score
pred = (p.predict(X) + 0.5).astype(int)
accuracy_score(pred, y)

0.7799479166666666

In [42]:
scores = []
for i in range(300):
    p = Perceptron(niter=i)
    p.fit(X, y)
    pred = (p.predict(X) + 0.5).astype(int)
    scores.append(accuracy_score(pred, y))
scores[-10:]

[0.7708333333333334,
 0.7708333333333334,
 0.7708333333333334,
 0.7708333333333334,
 0.7708333333333334,
 0.7708333333333334,
 0.7708333333333334,
 0.7708333333333334,
 0.7708333333333334,
 0.7708333333333334]

In [43]:
import matplotlib.pyplot as pyplot

pyplot.rcParams['figure.facecolor'] = '#002B36'
pyplot.rcParams['axes.facecolor'] = 'black'
pyplot.rcParams['figure.figsize'] = (10,8)

pyplot.plot(scores)
pyplot.yticks([i/100 for i in range(35,76,5)])
pyplot.ylabel('Accuracy')
pyplot.xlabel('Epochs')

pyplot.show()

<Figure size 1000x800 with 1 Axes>

## Stretch Goals:

- Research "backpropagation" to learn how weights get updated in neural networks (tomorrow's lecture). 
- Implement a multi-layer perceptron. (for non-linearly separable classes)
- Try and implement your own backpropagation algorithm.
- What are the pros and cons of the different activation functions? How should you decide between them for the different layers of a neural network?